### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by KayPure** [b3ck/server-bitrate-html#1]
Hey b3ck,

getting this error if i open up the edited html page. get the same error without the port. any ideas?
![Unbenannt](https://user-images.githubusercontent.com/43040621/140951976-78856eb3-8062-4492-9442-2a36b7ce187c.png)

**Comment by b3ck** [comment]
@KayPure did you figure this one out? you can always message me on Discord if you want: b3ck#3517

**Comment by KayPure** [comment]
@b3ck not yet. will msg u on discord if i get back to this, thx!

**Comment by b3ck** [comment]
looks like you are trying to pull it from port 1935, it should be like port 8080 or 8181, just check your config, the stats will be on a different port than the actual RTMP server, which uses port 1935 by default.

**Comment by KayPure** [comment]
ah doh! thank u very much. will change and test this asap

**Comment by KayPure** [comment]
Got it working. Chrome gave me this Error:

`from origin 'null' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'undefined'. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Stackoverflow gave me the Hint: 

`Origin null is the local file system, so that suggests that you're loading the HTML page that does the load call via a file:/// URL (e.g., just double-clicking it in a local file browser or similar).`

So i load the File in OBS via "LocalFile" as Browsersource. That fixed it for me ;)


![Unbenannt](https://user-images.githubusercontent.com/43040621/147965061-65a14951-d040-4fd5-8fe1-e43bb947a401.png)

**Comment by b3ck** [comment]
Sorry I should have made that more clear, that is the only way to add it as a browser source:

![image](https://user-images.githubusercontent.com/1740542/148205580-98a7b2a7-3f86-4125-a2fa-45319b1735d3.png)

**Comment by b3ck** [comment]
I have updated all of the readme files to account for this over look on my part, please make sure to check "local file" when adding it as a browser source in OBS.

**Comment by KayPure** [comment]
> Sorry I should have made that more clear, that is the only way to add it as a browser source:
> 
> ![image](https://user-images.githubusercontent.com/1740542/148205580-98a7b2a7-3f86-4125-a2fa-45319b1735d3.png)

No worries man, I could have thought of it sooner ;) thanks!
