### ISSUE TITLE
Can't seem to get bitrate.html for NGINX to work.

### ISSUE THREAD

**Issue by DigibitDK** [b3ck/server-bitrate-html#2]
Hi B3ck!

I have been trying to get bitrate.html to work for **NGINX**, but with no luck.

Im testing with a stream located in vod/resize1080, but that do not seem to add up with the configuration of the script in any way.

Im not even sure how your script should is able to fetch the incoming bitrate compared to stat-page code ... :/

Part of stat-page code:
```
<application>
<name>vod</name>
<live>
<stream>
<name>resize1080</name>
<time>277193732</time><bw_in>4485584</bw_in>
<bytes_in>146932524131</bytes_in>
<bw_out>0</bw_out>
<bytes_out>0</bytes_out>
<bw_audio>141064</bw_audio>
<bw_video>4344520</bw_video>
<client><id>6</id><address>127.0.0.1</address><time>277193732</time><dropped>0</dropped><avsync>17</avsync><timestamp>277193689</timestamp><publishing/><active/></client>
<meta><video><width>1920</width><height>1080</height><frame_rate>25</frame_rate><codec>H264</codec><profile>High</profile><compat>8</compat><level>5.0</level></video><audio><codec>MP3</codec><channels>2</channels><sample_rate>44100</sample_rate></audio></meta>
<nclients>1</nclients>
<publishing/>
<active/>
</stream>

```
![2022-01-22 10_50_03-Window](https://user-images.githubusercontent.com/69547207/150633680-f18a9582-3dd3-4c8f-b259-351772cdf1aa.png)

/Michael.

**Comment by DigibitDK** [comment]
I think I know what's wrong here. I managed to make it work, but it will not work the way described in the readme-file.

Ill explain to you on Discord later.

/Michael.

**Comment by b3ck** [comment]
it literally pulls from the stats page....

**Comment by b3ck** [comment]
so if your key is `vod/resize1080` then you would do `const live = parse.getElementsByTagName("vod/resize1080")[0];`

**Comment by b3ck** [comment]
I would also recommend you use the ALL SERVERS script: https://github.com/b3ck/server-bitrate-html/tree/master/ALL_SERVERS

**Comment by DigibitDK** [comment]
I have tried your suggestion but with no luck.

If you exchange 'live' with anything else than 'live', it will stop working.

If you create a simple Nginx-RTMP with 3 applications like this:
![2022-01-29 15_12_24-RTMP statistics](https://user-images.githubusercontent.com/69547207/151664358-eaa5c1f7-5d99-4bae-94ed-4834f2b261ed.png)

and keeps your code with the value 'live' as default, it will display anything that you put into application 1234 regardless of the key used, since its the first live-field on the stats-page.

Changing 'live' to something else, and it wont display anything at all.

Trying to use application test (or the key: 'hey') wont work in any way, unless its the first application on the stats-page.

Note: The value in 'setInterval(getBitrate, 2000);' do not seem to change anything (at least not in chrome) - It only refreshes every 10s regardless of value here.

I have only briefly tested All-Servers, but both scripts creates a bunch of errors in "Inspect > Console" in Chrome.

**Comment by b3ck** [comment]
show errors please

**Comment by timtam85465414** [comment]
Hi! Same problem for me, doesn't work with https://hub.docker.com/r/alfg/nginx-rtmp (i'm using key "live") :(

**Comment by b3ck** [comment]
I think using the `all_servers_bitrate` version fixes this issue, does it not?

**Comment by DigibitDK** [comment]
Hi again.
I dont know. I ended up creating a program that converts stat-pages into JSON-format like this:

{"name":"resize1080","time":154338869,"bw_in":4831440,"bytes_in":81810321735,"bw_out":0,"bytes_out":0,"bw_audio":140752,"bw_video":4690688,"meta":{"video":{"width":1920,"height":1080,"frame_rate":25,"codec":"H264","profile":"High","compat":8,"level":5},"audio":{"codec":"MP3","channels":2,"sample_rate":44100}},"nclients":1,"publishing":"","active":""}

and from there i can generate overlays etc. The main point of this is, that I dont have to expose complete stat-sites to public, and people can still get every information about a stream for whatever purpose they like.
